# Generated by Django 4.2.6 on 2023-10-12 21:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_remove_useractivity_user_alter_post_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="likes",
        ),
    ]
