# Generated by Django 4.2.6 on 2023-10-14 20:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0005_delete_useractivity_post_likes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="likes",
            field=models.ManyToManyField(
                null=True, related_name="liked_posts", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
